name: scalex_chatbot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_dotenv: ^6.0.0
  email_validator: ^3.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  jwt_decoder: ^2.0.1
  readmore: ^3.0.0
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^4.5.1
  async: ^2.11.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/lang/
    - .env